### ISSUE TITLE
UKS-1 - Create business object model

### ISSUE THREAD

**Issue by vujasinovic** [vujasinovic/UKS#1]
Make entity model based on provided uml diagram.

![uks-model](https://user-images.githubusercontent.com/26962017/74532565-cf685580-4f2f-11ea-88db-4c48c7d6be50.png)

**Comment by vujasinovic** [comment]
User entity should not contain foreign keys for Project and Issue entity.

**Comment by pavle-j4nk** [comment]
Please consider following corrections:
1) Considering that after completion of #12 application has [`auth_user`](https://docs.djangoproject.com/en/3.0/ref/contrib/auth/) table used for authentication, `uxhub_user` table should be replaced or linked with `auth_user`, so that currently signed user can access his projects.
2) As I understand, field `uxhub_issue.completion` represents state of issue (open or closed), therefore its type should be changed to enum (OPEN, CLOSED) or boolean
3) `uxhub_commit` should reference `uxhub_issue`
4) `uxhub_commit` should reference its author
